from jiminy.gym.envs.toy_text.blackjack import BlackjackEnv
from jiminy.gym.envs.toy_text.roulette import RouletteEnv
from jiminy.gym.envs.toy_text.frozen_lake import FrozenLakeEnv
from jiminy.gym.envs.toy_text.nchain import NChainEnv
from jiminy.gym.envs.toy_text.hotter_colder import HotterColder
from jiminy.gym.envs.toy_text.guessing_game import GuessingGame
from jiminy.gym.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from jiminy.gym.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from jiminy.gym.envs.toy_text.cliffwalking import CliffWalkingEnv
