version: '3.3'
##Start with docker-compose --compatibility up -d
services:
   vnc-remote:
     image: sibeshkar/jiminywob:latest
     privileged: true
     cap_add: ["SYS_ADMIN"]
     ipc: host
     command: ["run_firefox", "-f", "20"]
     deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
     ports:
       - "5908:5900"
       - "15908:15900"
       - "4808:6080"